using System.Collections.Generic;

namespace Sylvre.Core.Models
{
    /// <summary>
    /// Represents a JavaScript transpile output from the Sylvre transpiler.
    /// </summary>
    public class JavaScriptOutput : TranspileOutputBase
    {
        /// <summary>
        /// Initialises an instance of JavaScriptOutput with the given root context and collection of transpile errors.
        /// </summary>
        /// <param name="transpiledCode">The JavaScript code generated by the JavaScript transpiler.</param>
        /// <param name="transpileErrors">The collection of transpile errors encountered during transpiling.</param>
        public JavaScriptOutput(string transpiledCode,
            ICollection<SylvreTranspileError> transpileErrors) : base(transpiledCode, transpileErrors) { }
    }
}
