using static SylvreParser;

namespace Sylvre.Core.Models
{
    /// <summary>
    /// Represents a Sylvre program generated by parsing an input.
    /// </summary>
    public class SylvreProgram
    {
        /// <summary>
        /// The root of a Sylvre program concrete syntax tree generated by the parser.
        /// </summary>
        public ProgramContext SylvreCstRoot { get; private set; }

        /// <summary>
        /// Initialises a new instance of a SylvreProgram with the given root context.
        /// </summary>
        /// <param name="sylvreCstRoot">The root context of the concrete syntax tree generated by the parser.</param>
        public SylvreProgram(ProgramContext sylvreCstRoot)
        {
            SylvreCstRoot = sylvreCstRoot;
        }
    }
}
