using System;

using Sylvre.Core.Models;
using Sylvre.Core.Transpilers.JavaScript;

namespace Sylvre.Core
{
    /// <summary>
    /// The possible languages to transpile Sylvre to.
    /// </summary>
    public enum TargetLanguage { Javascript }

    /// <summary>
    /// Provides functionality to transpile a previously parsed Sylvre program.
    /// </summary>
    public static class Transpiler
    {
        /// <summary>
        /// Transpiles a given Sylvre program to the target language.
        /// </summary>
        /// <param name="sylvreProgram">The Sylvre program generated by parsing an input.</param>
        /// <param name="targetLanguage">The target language to transpile the Sylvre program to.</param>
        /// <returns>The transpiled output in the target language.</returns>
        public static TranspileOutputBase TranspileSylvreToTarget(SylvreProgram sylvreProgram,
            TargetLanguage targetLanguage)
        {
            switch (targetLanguage)
            {
                case TargetLanguage.Javascript:
                    return new JavaScriptTranspiler().Transpile(sylvreProgram);
                default:
                    throw new NotImplementedException();
            }
        }
    }
}
