using System;

using Sylvre.Core.Models;

namespace Sylvre.Core
{
    /// <summary>
    /// The possible languages to transpile Sylvre to.
    /// </summary>
    public enum TargetLanguage { Javascript }

    /// <summary>
    /// Provides functionality to transpile a previously parsed Sylvre program.
    /// </summary>
    public static class Transpiler
    {
        /// <summary>
        /// Transpiles a given Sylvre program to the target language.
        /// </summary>
        /// <param name="sylvreCST">The Sylvre program generated by parsing an input.</param>
        /// <param name="targetLanguage">The target language to transpile the Sylvre program to.</param>
        /// <exception cref="SylvreTranspileException">
        /// Thrown when transpiling Sylvre CST to output language failed.
        /// </exception>
        /// <returns>The transpiled output in the target language.</returns>
        public static TranspileOutputBase TranspileSylvreToTarget(SylvreProgram sylvreProgram, TargetLanguage targetLanguage)
        {
            throw new NotImplementedException();
        }
    }
}
