version: '3'

services:
  webapi:
    container_name: sylvre-webapi
    image: shahzaibm/sylvre-webapi:latest
    hostname: sylvre-webapi
    ports:
      - 50005:80
    environment:
      APPSETTINGS__SECRET: ${SYLVREWEBAPI_SECRET}
      APPSETTINGS__CORSORIGIN: ${SYLVREWEBAPI_CORSORIGIN}
      APPSETTINGS__COOKIEDOMAIN: ${SYLVREWEBAPI_COOKIEDOMAIN}
      APPSETTINGS__APIDOCSROOTURL: ${SYLVREWEBAPI_APIDOCSROOTURL}
      CONNECTIONSTRINGS__SYLVREWEBAPIDBCONNECTION: "User ID=sylvre-webapi;Password=password;Server=sylvre-webapi-db;Port=5432;Database=sylvre-webapi;Integrated Security=true;Pooling=true;"
    depends_on:
      - "db"
    restart: always

  db:
    container_name: sylvre-webapi-db
    image: postgres
    hostname: sylvre-webapi-db
    environment:
      POSTGRES_USER: "sylvre-webapi"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "sylvre-webapi"
    volumes:
      - ${DATABASE_PATH_ON_HOST}:/var/lib/postgresql/data
    restart: always
