version: '3'

services:
  webapi:
    container_name: sylvre-webapi
    image: shahzaibm/sylvre-webapi:latest
    hostname: sylvre-webapi
    environment:
      APPSETTINGS__SECRET: ${SYLVREWEBAPI_SECRET}
      APPSETTINGS__CORSORIGIN: ${SYLVREWEBAPI_CORSORIGIN}
      APPSETTINGS__COOKIEDOMAIN: ${SYLVREWEBAPI_COOKIEDOMAIN}
      CONNECTIONSTRINGS__SYLVREWEBAPIDBCONNECTION: "User ID=sylvre-webapi;Password=password;Server=sylvre-webapi-db;Port=5432;Database=sylvre-webapi;Integrated Security=true;Pooling=true;"
      VIRTUAL_HOST: ${SYLVREWEBAPI_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${SYLVREWEBAPI_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${SYLVREWEBAPI_LETSENCRYPT_EMAIL}
    expose:
      - "80"
    depends_on:
      - "db"
    restart: unless-stopped

  db:
    container_name: sylvre-webapi-db
    image: postgres
    hostname: sylvre-webapi-db
    environment:
      POSTGRES_USER: "sylvre-webapi"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "sylvre-webapi"
    volumes:
      - sylvre-webapi-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sylvre-webapi-db-data:
