version: '3'

services:
  webapi:
    container_name: sylvre-webapi
    image: shahzaibm/sylvre-webapi:latest
    hostname: sylvre-webapi
    ports:
      - ${API_PORT_ON_HOST}:80
    environment:
      APPSETTINGS__SYLAPI_SECRET: ${SYLVREWEBAPI_SECRET}
      APPSETTINGS__SYLAPI_CORSORIGIN: ${SYLVREWEBAPI_CORSORIGIN}
      APPSETTINGS__SYLAPI_COOKIEDOMAIN: ${SYLVREWEBAPI_COOKIEDOMAIN}
      APPSETTINGS__SYLAPI_DBSERVER: "sylvre-webapi-db"
      APPSETTINGS__SYLAPI_DBPORT: "5432"
      APPSETTINGS__SYLAPI_DBNAME: "sylvre-webapi"
      APPSETTINGS__SYLAPI_DBUSER: "sylvre-webapi"
      APPSETTINGS__SYLAPI_DBPASSWORD: "password"
    depends_on:
      - "db"
    restart: always

  db:
    container_name: sylvre-webapi-db
    image: postgres
    hostname: sylvre-webapi-db
    environment:
      POSTGRES_USER: "sylvre-webapi"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "sylvre-webapi"
    volumes:
      - ${DATABASE_PATH_ON_HOST}:/var/lib/postgresql/data
    restart: always
