//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\SylvreParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SylvreParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
//[System.CLSCompliant(false)]
public interface ISylvreParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SylvreParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.seperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeperator([NotNull] SylvreParser.SeperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SylvreParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.nestable_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestable_block([NotNull] SylvreParser.Nestable_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.use_file_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUse_file_statement([NotNull] SylvreParser.Use_file_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.statement_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_block([NotNull] SylvreParser.Statement_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.function_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_block([NotNull] SylvreParser.Function_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.if_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_block([NotNull] SylvreParser.If_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.elseif_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseif_block([NotNull] SylvreParser.Elseif_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.else_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_block([NotNull] SylvreParser.Else_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.loopwhile_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopwhile_block([NotNull] SylvreParser.Loopwhile_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.loopfor_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopfor_block([NotNull] SylvreParser.Loopfor_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_expression([NotNull] SylvreParser.Conditional_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_operator([NotNull] SylvreParser.Comparison_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.logical_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_operator([NotNull] SylvreParser.Logical_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] SylvreParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] SylvreParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] SylvreParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SylvreParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] SylvreParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] SylvreParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] SylvreParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.array_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_assignment([NotNull] SylvreParser.Array_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.array_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_elements([NotNull] SylvreParser.Array_elementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] SylvreParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.function_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_return([NotNull] SylvreParser.Function_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.function_return_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_return_value([NotNull] SylvreParser.Function_return_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SylvreParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] SylvreParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] SylvreParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.arithmetic_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmetic_operator([NotNull] SylvreParser.Arithmetic_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] SylvreParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.variable_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_reference([NotNull] SylvreParser.Variable_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.variable_complex_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_complex_reference([NotNull] SylvreParser.Variable_complex_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.variable_complex_reference_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_complex_reference_left([NotNull] SylvreParser.Variable_complex_reference_leftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.variable_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_suffix([NotNull] SylvreParser.Variable_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.variable_suffix_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_suffix_left([NotNull] SylvreParser.Variable_suffix_leftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.member_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_reference([NotNull] SylvreParser.Member_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.member_reference_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_reference_left([NotNull] SylvreParser.Member_reference_leftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.index_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_reference([NotNull] SylvreParser.Index_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.unary_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_increment([NotNull] SylvreParser.Unary_incrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.unary_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_decrement([NotNull] SylvreParser.Unary_decrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.unary_prefix_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_prefix_increment([NotNull] SylvreParser.Unary_prefix_incrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.unary_prefix_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_prefix_decrement([NotNull] SylvreParser.Unary_prefix_decrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.unary_suffix_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_suffix_increment([NotNull] SylvreParser.Unary_suffix_incrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SylvreParser.unary_suffix_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_suffix_decrement([NotNull] SylvreParser.Unary_suffix_decrementContext context);
}
