//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\SylvreParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SylvreParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
//[System.CLSCompliant(false)]
public interface ISylvreParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] SylvreParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] SylvreParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.seperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeperator([NotNull] SylvreParser.SeperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.seperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeperator([NotNull] SylvreParser.SeperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] SylvreParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] SylvreParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.nestable_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestable_block([NotNull] SylvreParser.Nestable_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.nestable_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestable_block([NotNull] SylvreParser.Nestable_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.use_file_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUse_file_statement([NotNull] SylvreParser.Use_file_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.use_file_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUse_file_statement([NotNull] SylvreParser.Use_file_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.statement_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_block([NotNull] SylvreParser.Statement_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.statement_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_block([NotNull] SylvreParser.Statement_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_block([NotNull] SylvreParser.Function_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_block([NotNull] SylvreParser.Function_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.if_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_block([NotNull] SylvreParser.If_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.if_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_block([NotNull] SylvreParser.If_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.elseif_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseif_block([NotNull] SylvreParser.Elseif_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.elseif_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseif_block([NotNull] SylvreParser.Elseif_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.else_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_block([NotNull] SylvreParser.Else_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.else_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_block([NotNull] SylvreParser.Else_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.loopwhile_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopwhile_block([NotNull] SylvreParser.Loopwhile_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.loopwhile_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopwhile_block([NotNull] SylvreParser.Loopwhile_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.loopfor_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopfor_block([NotNull] SylvreParser.Loopfor_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.loopfor_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopfor_block([NotNull] SylvreParser.Loopfor_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_expression([NotNull] SylvreParser.Conditional_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_expression([NotNull] SylvreParser.Conditional_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_operator([NotNull] SylvreParser.Comparison_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_operator([NotNull] SylvreParser.Comparison_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.logical_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_operator([NotNull] SylvreParser.Logical_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.logical_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_operator([NotNull] SylvreParser.Logical_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] SylvreParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] SylvreParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] SylvreParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] SylvreParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] SylvreParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] SylvreParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SylvreParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SylvreParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] SylvreParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] SylvreParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] SylvreParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] SylvreParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_operator([NotNull] SylvreParser.Assignment_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_operator([NotNull] SylvreParser.Assignment_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.array_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_assignment([NotNull] SylvreParser.Array_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.array_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_assignment([NotNull] SylvreParser.Array_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.array_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_elements([NotNull] SylvreParser.Array_elementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.array_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_elements([NotNull] SylvreParser.Array_elementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call([NotNull] SylvreParser.Function_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call([NotNull] SylvreParser.Function_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_return([NotNull] SylvreParser.Function_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_return([NotNull] SylvreParser.Function_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_return_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_return_value([NotNull] SylvreParser.Function_return_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_return_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_return_value([NotNull] SylvreParser.Function_return_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] SylvreParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] SylvreParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] SylvreParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] SylvreParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] SylvreParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] SylvreParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.arithmetic_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmetic_operator([NotNull] SylvreParser.Arithmetic_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.arithmetic_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmetic_operator([NotNull] SylvreParser.Arithmetic_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] SylvreParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] SylvreParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_reference([NotNull] SylvreParser.Variable_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_reference([NotNull] SylvreParser.Variable_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_complex_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_complex_reference([NotNull] SylvreParser.Variable_complex_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_complex_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_complex_reference([NotNull] SylvreParser.Variable_complex_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_complex_reference_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_complex_reference_left([NotNull] SylvreParser.Variable_complex_reference_leftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_complex_reference_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_complex_reference_left([NotNull] SylvreParser.Variable_complex_reference_leftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_suffix([NotNull] SylvreParser.Variable_suffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_suffix([NotNull] SylvreParser.Variable_suffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_suffix_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_suffix_left([NotNull] SylvreParser.Variable_suffix_leftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_suffix_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_suffix_left([NotNull] SylvreParser.Variable_suffix_leftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.member_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_reference([NotNull] SylvreParser.Member_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.member_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_reference([NotNull] SylvreParser.Member_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.member_reference_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_reference_left([NotNull] SylvreParser.Member_reference_leftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.member_reference_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_reference_left([NotNull] SylvreParser.Member_reference_leftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.index_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_reference([NotNull] SylvreParser.Index_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.index_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_reference([NotNull] SylvreParser.Index_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_increment([NotNull] SylvreParser.Unary_incrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_increment([NotNull] SylvreParser.Unary_incrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_decrement([NotNull] SylvreParser.Unary_decrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_decrement([NotNull] SylvreParser.Unary_decrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_prefix_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_prefix_increment([NotNull] SylvreParser.Unary_prefix_incrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_prefix_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_prefix_increment([NotNull] SylvreParser.Unary_prefix_incrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_prefix_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_prefix_decrement([NotNull] SylvreParser.Unary_prefix_decrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_prefix_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_prefix_decrement([NotNull] SylvreParser.Unary_prefix_decrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_suffix_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_suffix_increment([NotNull] SylvreParser.Unary_suffix_incrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_suffix_increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_suffix_increment([NotNull] SylvreParser.Unary_suffix_incrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_suffix_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_suffix_decrement([NotNull] SylvreParser.Unary_suffix_decrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_suffix_decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_suffix_decrement([NotNull] SylvreParser.Unary_suffix_decrementContext context);
}
