//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./SylvreParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISylvreParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SylvreParserBaseListener : ISylvreParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] SylvreParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] SylvreParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.seperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeperator([NotNull] SylvreParser.SeperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.seperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeperator([NotNull] SylvreParser.SeperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] SylvreParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] SylvreParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.nestable_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestable_block([NotNull] SylvreParser.Nestable_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.nestable_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestable_block([NotNull] SylvreParser.Nestable_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.use_file_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUse_file_statement([NotNull] SylvreParser.Use_file_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.use_file_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUse_file_statement([NotNull] SylvreParser.Use_file_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.statement_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_block([NotNull] SylvreParser.Statement_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.statement_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_block([NotNull] SylvreParser.Statement_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_block([NotNull] SylvreParser.Function_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_block([NotNull] SylvreParser.Function_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.if_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_block([NotNull] SylvreParser.If_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.if_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_block([NotNull] SylvreParser.If_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.elseif_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseif_block([NotNull] SylvreParser.Elseif_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.elseif_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseif_block([NotNull] SylvreParser.Elseif_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.else_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_block([NotNull] SylvreParser.Else_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.else_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_block([NotNull] SylvreParser.Else_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.loopwhile_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopwhile_block([NotNull] SylvreParser.Loopwhile_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.loopwhile_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopwhile_block([NotNull] SylvreParser.Loopwhile_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.loopfor_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopfor_block([NotNull] SylvreParser.Loopfor_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.loopfor_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopfor_block([NotNull] SylvreParser.Loopfor_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_expression([NotNull] SylvreParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_expression([NotNull] SylvreParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.comparison_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_operator([NotNull] SylvreParser.Comparison_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.comparison_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_operator([NotNull] SylvreParser.Comparison_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.logical_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_operator([NotNull] SylvreParser.Logical_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.logical_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_operator([NotNull] SylvreParser.Logical_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] SylvreParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] SylvreParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] SylvreParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] SylvreParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] SylvreParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] SylvreParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SylvreParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SylvreParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] SylvreParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] SylvreParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] SylvreParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] SylvreParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_operator([NotNull] SylvreParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_operator([NotNull] SylvreParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.array_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_assignment([NotNull] SylvreParser.Array_assignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.array_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_assignment([NotNull] SylvreParser.Array_assignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.array_elements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_elements([NotNull] SylvreParser.Array_elementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.array_elements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_elements([NotNull] SylvreParser.Array_elementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call([NotNull] SylvreParser.Function_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call([NotNull] SylvreParser.Function_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_return([NotNull] SylvreParser.Function_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_return([NotNull] SylvreParser.Function_returnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.function_return_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_return_value([NotNull] SylvreParser.Function_return_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.function_return_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_return_value([NotNull] SylvreParser.Function_return_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] SylvreParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] SylvreParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] SylvreParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] SylvreParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] SylvreParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] SylvreParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.arithmetic_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmetic_operator([NotNull] SylvreParser.Arithmetic_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.arithmetic_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmetic_operator([NotNull] SylvreParser.Arithmetic_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] SylvreParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] SylvreParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_reference([NotNull] SylvreParser.Variable_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_reference([NotNull] SylvreParser.Variable_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_complex_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_complex_reference([NotNull] SylvreParser.Variable_complex_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_complex_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_complex_reference([NotNull] SylvreParser.Variable_complex_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_complex_reference_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_complex_reference_left([NotNull] SylvreParser.Variable_complex_reference_leftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_complex_reference_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_complex_reference_left([NotNull] SylvreParser.Variable_complex_reference_leftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_suffix([NotNull] SylvreParser.Variable_suffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_suffix([NotNull] SylvreParser.Variable_suffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.variable_suffix_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_suffix_left([NotNull] SylvreParser.Variable_suffix_leftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.variable_suffix_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_suffix_left([NotNull] SylvreParser.Variable_suffix_leftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.member_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_reference([NotNull] SylvreParser.Member_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.member_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_reference([NotNull] SylvreParser.Member_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.member_reference_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_reference_left([NotNull] SylvreParser.Member_reference_leftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.member_reference_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_reference_left([NotNull] SylvreParser.Member_reference_leftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.index_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_reference([NotNull] SylvreParser.Index_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.index_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_reference([NotNull] SylvreParser.Index_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_increment([NotNull] SylvreParser.Unary_incrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_increment([NotNull] SylvreParser.Unary_incrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_decrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_decrement([NotNull] SylvreParser.Unary_decrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_decrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_decrement([NotNull] SylvreParser.Unary_decrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_prefix_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_prefix_increment([NotNull] SylvreParser.Unary_prefix_incrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_prefix_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_prefix_increment([NotNull] SylvreParser.Unary_prefix_incrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_prefix_decrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_prefix_decrement([NotNull] SylvreParser.Unary_prefix_decrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_prefix_decrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_prefix_decrement([NotNull] SylvreParser.Unary_prefix_decrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_suffix_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_suffix_increment([NotNull] SylvreParser.Unary_suffix_incrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_suffix_increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_suffix_increment([NotNull] SylvreParser.Unary_suffix_incrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SylvreParser.unary_suffix_decrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_suffix_decrement([NotNull] SylvreParser.Unary_suffix_decrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SylvreParser.unary_suffix_decrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_suffix_decrement([NotNull] SylvreParser.Unary_suffix_decrementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
