name: Build combined Sylvre Docker image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'core-and-webapi/Sylvre.Core/**'
      - 'core-and-webapi/Sylvre.WebAPI/**'
      - 'webapp-client/public/**'
      - 'webapp-client/src/**'
      - 'webapp-client/*.json'
      - 'webapp-client/*.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet

    - name: Extract version
      id: get_version
      run: |
        VERSION=$(xmlstarlet sel -t -v "//Project/PropertyGroup/Version" core-and-webapi/Sylvre.WebAPI/Sylvre.WebAPI.csproj)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Log in to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push
      run: |
        IMAGE_NAME=ghcr.io/shahzaib-m/sylvre
        VERSION=${{ env.VERSION }}
        docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:$VERSION
        docker push $IMAGE_NAME:latest
