# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Sylvre Unit Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: src/Sylvre.Tests
      run: dotnet restore
    - name: Build
      working-directory: src/Sylvre.Tests
      run: dotnet build --no-restore
    - name: Test
      working-directory: src/Sylvre.Tests
      run: dotnet test --no-build --verbosity normal
